export default {
  URL_RESET_PASSWORD: process.env.URL_RESET_PASSWORD,
  URL_EMAIL_UNSUBSCRIBE: process.env.URL_EMAIL_UNSUBSCRIBE,
  URL_CONFIRM_EMAIL: process.env.URL_CONFIRM_EMAIL,
  EMAIL_SUPPORT: process.env.EMAIL_SUPPORT
};
