export default {
  USERS_API_URL: process.env.URL_RESOURCES_API + '/users',
  URL_EMAIL_VERIFY_SUCCESS: process.env.URL_EMAIL_VERIFY_SUCCESS,
  URL_EMAIL_VERIFY_FAIL: process.env.URL_EMAIL_VERIFY_FAIL,
  URL_EMAIL_UNSUBSCRIBE: process.env.URL_EMAIL_UNSUBSCRIBE,
  URL_CONFIRM_EMAIL: process.env.URL_CONFIRM_EMAIL,
  EMAIL_SUPPORT: process.env.EMAIL_SUPPORT
};
